name: Build macOS x86_64
on:
  push:
    tags:
      - '*'
jobs:
  macOS:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./make.rb macos-x86_64
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/macos-x86_64/bismite-sprite-sheeter.tgz
          asset_name: bismite-sprite-sheeter-macos-x86_64-${{github.ref_name}}.tgz
          overwrite: true
